#!/bin/bash

# Add here any the actions which are required before plugin build
# like packages building, packages downloading from mirrors and so on.
# The script should return 0 if there were no errors.

cd deployment_scripts/puppet/modules/puppet-manila && git pull || \
cd deployment_scripts/puppet/modules; \
git clone -b stable/mitaka https://github.com/openstack/puppet-manila.git
