#!/bin/bash

git submodule update

function build_deb {
    version=$1
    src=$2
    name=$3
    fpm -v $version -s python -t deb -n $name --python-install-bin /usr/bin --python-install-lib /usr/lib/python2.7/dist-packages/ $src/setup.py
}


rm repositories/ubuntu/*
cd repositories/python

build_deb "1:2.0.1" manila fuel-plugin-manila-manila-core

sed -i s/'python-keystoneclient'/'#python-keystoneclient'/ manila-ui/requirements.txt
sed -i s/'python-manilaclient'/'#python-manilaclient'/ manila-ui/requirements.txt
sed -i s/'disabled_quotas.extend(_get_manila_disabled_quotas(request))'/'disabled_quotas.update(_get_manila_disabled_quotas(request))'/ manila-ui/manila_ui/dashboards/project/shares/__init__.py
build_deb 2.1.1 manila-ui fuel-plugin-manila-manila-ui
cd manila-ui; git checkout stable/mitaka;
git checkout -- requirements.txt;
git checkout -- manila_ui/dashboards/project/shares/__init__.py
cd ..

mv *.deb ../ubuntu
